# Copyright (c) 2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Oracle Logging Analytics Quick Start"
stackDescription: "This is a OCI (Oracle Cloud Infrastructure) Logging Analytics Quick Start automation. 
It creates all the necessary OCI resources 
* Create Logging Analytics User Group 
* Create Logging Analytics Users 
* Create Dynamic Groups
* Create Logging Analytics Policies
* Onboard Logging Analytics

All this is done using terraform."

schemaVersion: 1.1.0
version: "20190304"
logoUrl: "https://cloudmarketplace.oracle.com/marketplace/content?contentId=58352039"
source:
  type: marketplace
  reference: 47726045

locale: "en"
variableGroups:
  - title: General Configuration
    visible: false
    variables:
      - tenancy_ocid
      - compartment_ocid
      - compartment_id
      - region

  - title: Optional Configuration
    variables:
      - create_compartment
      - compartment_ocid
      - logging_analytics_compartment_name
      - create_user
      - logging_analytics_user_email
      - logging_analytics_user_name
      - onboard_logging_analytics
      
  - title: Required Configuration
    variables:
      - logging_analytics_group_name
      - loganalytics_dynamic_group_name
      - logging_analytics_policy_name

  - title: Enable Audit Logs
    variables:
      - create_log_analytics_audit_log_group
      - log_analytics_audit_log_group_name
      - audit_service_connector_name
    
variables:
  create_compartment:
    type: enum
    title: Create New Logging Analytics Compartment ?
    enum:
      - "yes"
      - "no"
    default: "no"
    required: true
  
  compartment_ocid:
    type: oci:identity:compartment:id
    title: Select Existing Logging Analytics Compartment
    description: Select the existing compartment
    default: compartment_ocid
    required: true
    visible:
      eq:
        - create_compartment
        - "no"
  
  logging_analytics_compartment_name:
    type: string
    title: New Logging Analytics Compartment Name
    default: "Logging-Analytics-Compartment"
    required: true
    visible:
      eq:
        - create_compartment
        - "yes"

  onboard_logging_analytics:
    type: enum
    title: Onboard Logging Analytics Namespace ?
    enum:
      - "yes"
      - "no"
    default: "no"
    required: true
  
  logging_analytics_group_name:
    title: Logging Analytics Admin IAM group name
    default: "Logging-Analytics-SuperAdmins"
    required: true

  create_user:
    type: enum
    title: Create New Logging Analytics User ?
    enum:
      - "yes"
      - "no"
    default: "no"
    required: true
  
  logging_analytics_user_name:
    title: Logging Analytics User name
    default: "Logging-Analytics-User-01"
    required: true
    visible:
      eq:
        - create_user
        - "yes"
  
  logging_analytics_user_email:
    title: logging analytics New User Email
    description: This will create a new user and sends the activation email.
    default: "Logging_Analytics_User_Email@oracle.com"
    required: true
    visible:
      eq:
        - create_user
        - "yes"

  loganalytics_dynamic_group_name:
    title: Logging Analytics dynamic group name
    default: "ManagementAgentAdmins"
    required: true
    
  logging_analytics_policy_name:
    title: Logging Analytics Policy name
    default: "Logging-Analytics-Policy"
    required: true
  
  create_log_analytics_audit_log_group:
    type: enum
    title: Enable Audit logs collection on Logging Analytics ?
    enum:
      - "yes"
      - "no"
    default: "no"
    required: true
  
  log_analytics_audit_log_group_name:
    title: Logging Analytics Log Group Name
    description: This will create a new Logging Analytics Log Group Name.
    required: true
    default: "audit-loganalytics-group"
    visible:
      eq:
        - create_log_analytics_audit_log_group
        - "yes"
      
  audit_service_connector_name:
    title: Audit Service Connector Hub from Logging to loganalytics
    description: This will create a Audit Service Connector Hub from Logging to loganalytics.
    required: true
    default: "audit-logging-to-loganalytics"
    visible:
      eq:
        - create_log_analytics_audit_log_group
        - "yes"
      
  
outputGroups:
  - title: Logging Analytics Configuration
    outputs:
      - ${logging_analytics_config}
