# Copyright (c) 2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Oracle Logging Analytics Quick Start"
stackDescription: "This is a OCI (Oracle Cloud Infrastructure) Logging Analytics Quick Start automation. 
It creates all the necessary OCI resources 
* Create Logging Analytics User Group 
* Create Logging Analytics Users 
* Create Dynamic Groups
* Create Logging Analytics Policies
* Onboard Logging Analytics
All this is done using terraform."

schemaVersion: 1.1.0
version: "20190304"

logoUrl: "https://cloudmarketplace.oracle.com/marketplace/content?contentId=58352039"

source:
  type: marketplace
  reference: 47726045

locale: "en"

variableGroups:
  - title: General Configuration
    visible: false
    variables:
      - tenancy_ocid
      - compartment_ocid
      - region

  - title: Optional Configuration
    visible: true  
    variables:
      - log_analytics_namespace
      - logging_analytics_user_email
    
variables:
  log_analytics_namespace:
    title: Logging Analytics Namespace for onboarding a tenancy (Tenancy Name)
    required: false
    default: ""
  logging_analytics_user_email:
      title: logging analytics New User Email
      description: This will create a new user and sends the activation email. If not provided, it creates a user with dummy email.
      required: false
      default: ""

 
outputGroups:
  - title: Logging Analytics Configuration
    outputs:
      - ${logging_analytics_config}
