# Copyright (c) 2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Oracle Logging Analytics Quick Start"
stackDescription: "This is a OCI (Oracle Cloud Infrastructure) Logging Analytics Quick Start automation. 
It creates all the necessary OCI resources 
* Create Logging Analytics User Group 
* Create Logging Analytics Policies
* Onboard Logging Analytics"

schemaVersion: 1.1.0
version: "20190304"
logoUrl: "https://cloudmarketplace.oracle.com/marketplace/content?contentId=58352039"
source:
  type: marketplace
  reference: 47726045

locale: "en"
variableGroups:
  - title: General Configuration
    visible: false
    variables:
      - tenancy_ocid
      - compartment_ocid
      - compartment_id
      - region

  - title: Oracle Logging Analytics Quick Start
    variables:
      - identity_domain_enabled
      - compartment_ocid
      #- onboard_logging_analytics

  - title: Required Identity & Management Configuration
    variables:
      - identity_domain_url
      - create_logging_analytics_group
      - logging_analytics_group_name
      - existing_logging_analytics_group_name
      #- loganalytics_dynamic_group_name
      #- logging_analytics_policy_name

  - title: Enabling Audit Logs
    variables:
      - create_log_analytics_audit_log_group
      #- log_analytics_audit_log_group_name
      #- audit_service_connector_name
    
variables:
  identity_domain_enabled:
    type: enum
    title: Does this tenancy have identity domains enabled ? 
    enum:
      - "yes"
      - "no"
    default: "no"
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    title: Select Existing Logging Analytics Compartment
    description: Select the existing compartment
    default: compartment_ocid
    required: true
   
  # onboard_logging_analytics:
  #   type: enum
  #   title: Onboard Logging Analytics Namespace ?
  #   enum:
  #     - "yes"
  #     - "no"
  #   default: "no"
  #   required: true

  identity_domain_url:
    title: OCI Identity Domain URL
    description: "OCI Identity Domain URL"
    required: true
    visible:
      eq:
        - identity_domain_enabled
        - "yes"
  
  create_logging_analytics_group:
    type: enum
    title: Create a New Logging Analytics Admins IAM group ?
    enum:
      - "yes"
      - "no"
    default: "no"
    required: true

  logging_analytics_group_name:
    title: Logging Analytics Admins IAM group name
    description: "This will create a new IAM Group to be used by Logging Analytics Admins"
    required: true
    visible:
      eq:
        - create_logging_analytics_group
        - "yes"

  existing_logging_analytics_group_name:
    title: Existing IAM Group Name
    description: "Provide existing IAM Group to use"
    required: true
    visible:
      eq:
        - create_logging_analytics_group
        - "no"

  #loganalytics_dynamic_group_name:
  #  title: Logging Analytics dynamic group name
  #  default: "management-agent-admins"
  #  required: true
    
  # logging_analytics_policy_name:
  #   title: Logging Analytics Policy name
  #   default: "logging-analytics-policy"
  #   required: true
  
  create_log_analytics_audit_log_group:
    type: enum
    title: Enable Audit logs collection on Logging Analytics ?
    enum:
      - "yes"
      - "no"
    default: "no"
    required: true
  
  # log_analytics_audit_log_group_name:
  #   title: Logging Analytics Log Group Name
  #   description: This will create a new OCI Logging Analytics Log Group Name.
  #   required: true
  #   default: "audit-loganalytics-group"
  #   visible:
  #     eq:
  #       - create_log_analytics_audit_log_group
  #       - "yes"
      
  # audit_service_connector_name:
  #   title: Audit Service Connector Hub from OCI Logging to logging analytics
  #   description: This will create a Audit Service Connector Hub from OCI Logging to logging analytics.
  #   required: true
  #   default: "audit-logs-sch-connector"
  #   visible:
  #     eq:
  #       - create_log_analytics_audit_log_group
  #       - "yes"
      
outputGroups:
  - title: Logging Analytics Configuration
    outputs:
      - ${logging_analytics_config}
